version: '3.9'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./
    expose:
    - 8000
      #    ports:
            #      - '8000:8000'
#      - 127.0.0.1:8000:8000

  nginx:
    restart: unless-stopped
    build: 
      context: ./nginx
#      dockerfile: ./nginx/Dockerfile
    ports:
    - '80:80'
    - '443:443'
    depends_on:
    - client
    volumes:
    - ./certs/:/etc/ssl/

